server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/goal_app_db
    username: postgres
    password: pdntspa
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    baseline-on-migrate: true

